### ISSUE TITLE
Texts aren't properly visible in light mode

### ISSUE THREAD

**Issue by GautamCoder4019k** [PratyushSingh07/IssueHive#38]
some text on the home screen fragment is not visible when the dark mode of device is off.

When dark mode is off

<img src=https://github.com/PratyushSingh07/IssueHive/assets/123801344/d5e49e6e-6d93-4649-afe1-1a346e494baf  width="250" height="500">

When dark mode is on

<img src=https://github.com/PratyushSingh07/IssueHive/assets/123801344/3f00a81b-6b13-4591-9063-d83024b96969  width="250" height="500">

**Comment by PratyushSingh07** [comment]
Thanks for this issue. Can you just edit your issue to something like "Texts aren't properly visible in the light mode"

Also is this issue only in the home fragment? Have you checked this in other fragments as well

**Comment by PratyushSingh07** [comment]
Then please open a PR that fixes this behaviour in all of the fragments

**Comment by PratyushSingh07** [comment]
are you going to raise a PR for this issue @GautamCoder4019k ?
